name: Push to Develop

# on:
#   pull_request:
#     types: [ closed ]
#     branches: [ "develop" ]

on:
  push:
    branches: [ "develop" ]

jobs:
  central:
    uses: canpolato/core-pipelines/.github/workflows/core-push-develop.yml@main
    secrets: inherit