name: Push to Release

on:
  push:
    branches: [ "release/*" ]

jobs:
  central:
    # if: github.event.created == false
    uses: canpolato/core-pipelines/.github/workflows/core-push-release.yml@main
    secrets: inherit